index/urls.py
#-*- coding : utf-8 -*-
# coding: utf-8
# @time：2021/4/20 11:56
# @Author：yanl
# @File    : urls.py
# @Software: PyCharm
from django.conf.urls import url
from django.urls import path
from index import views

app_name = 'index'

urlpatterns = [
    url('^$', views.home, name='home'),  # 首页路由
    url('home', views.home, name='home'),  # 首页路由

    url('^yyrb$', views.yyrb, name='yyrb'),  # 医院日报
    url('^mzybbl$', views.mzybbl, name='mzybbl'),  # 门诊药比 比例
    url('^mzyb$', views.mzyb, name='mzyb'),  # 门诊药比

    url('^zyyb$', views.zyyb, name='zyyb'), # 住院药比
    url('^zyybbl$', views.zyybbl, name='zyybbl'), # 住院药比
    url('mzyb', views.mzyb, name='mzyb'), # 门诊药比


    # 获取数据
    url('getZyybData', views.getZyybData, name='getZyybData')  # 获取数据并保存到mysql中

]

reportForm/urls.py
from django.contrib import admin
from django.urls import path, include
from index import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='index'))
]


# 创建定时任务
# from apscheduler.scheduler import Scheduler
# from index.views import getdataeveryday
#
# sched = Scheduler()
#
# @sched.interval_schedule(seconds=3000000)
# def mytask():
#     getdataeveryday()
# sched.start()

index/models.py
from django.db import models

# Create your models here.

index/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from util import linkDB, getDBData
import json
import os
import pandas as pd
from util.getDBData import getData2,getData,toMysql

# Create your views here.

def home(request):
    return render(request, 'home.html')

def yyrb(request):
    if request.method == 'GET':
        return render(request, 'yyrb.html')
    else:
        dataset = 111
        return HttpResponse(dataset, content_type="application/json")

def mzybbl(request):
    pass


def zyyb(request):
    if request.method == 'GET':
        return render(request, 'zyyb.html')
    elif request.method == 'POST':
        starttime = request.POST.get("time")[:10]
        endtime = request.POST.get("time")[13:]
        # windows下路径
        # sqlfile = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), 'sql\住院药比金额mysql.sql')
        # mac环境下路径
        sqlfile = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), 'sql/住院药比金额mysql.sql')
        # print(sqlfile)
        df = getDBData.getData(sqlfile, 'mysql', starttime, endtime)
        dataset = df.to_json(orient="table", force_ascii=False)
        datadict = json.loads(dataset)
        # 添加状态信息，状态为1 为检索成功。状态为0 为检索失败
        datadict["status"] = 1
        dataset = json.dumps(datadict)
        print("sql查询成功！！！！！！！！！")
        return HttpResponse(dataset, content_type="application/json")

def zyybbl(request):
    if request.method == 'GET':
        return render(request, 'zyybbl.html')
    elif request.method == 'POST':
        starttime = request.POST.get("time")[:10]
        endtime = request.POST.get("time")[13:]
        # windows下路径
        # sqlfile = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), 'sql\住院药比金额mysql.sql')
        # mac环境下路径
        sqlfile = os.path.join(os.path.abspath(os.path.dirname(os.path.dirname(__file__))), 'sql/住院药比比例mysql.sql')
        # print(sqlfile)
        df = getDBData.getData(sqlfile, 'mysql', starttime, endtime)
        dataset = df.to_json(orient="table", force_ascii=False)
        datadict = json.loads(dataset)
        # 添加状态信息，状态为1 为检索成功。状态为0 为检索失败
        datadict["status"] = 1
        dataset = json.dumps(datadict)
        print("sql查询成功！！！！！！！！！")
        return HttpResponse(dataset, content_type="application/json")

def mzyb(request):
    pass

def getZyybData(request):
    if request.method == 'GET':
        # dataset = json.dumps("请提交数据")
        dataset = "请提交数据"
        return HttpResponse(dataset, content_type="text/html;charset=UTF-8")
    elif request.method == 'POST':
        req = json.loads(request.body)
        print(req)
        DBtable = 'zyyb'
        df = pd.read_json(req, orient='index')
        # 由于科室编码 有部分为 0 开头的 对此进行处理
        df['dept_code'] = [i[1:5] for i in df['dept_code']]
        # print(df)
        now_time = df['create_date'][0]
        # 判断该日期是否有数据
        sqlfile1 = './sql/查询某日期表中是否有数据.sql'
        res = getData2(sqlfile1, 'mysql', DBtable, now_time)
        # 先判断表中是否有该天的数据，如果有 则不抽取数据
        if len(res) == 0:
            try:
                toMysql(df, DBtable)
                print('住院药比 --- 数据插入成功 ')
            except Exception as e:
                print('住院药比 --- 数据插入失败！！！！ ')
        else:
            print(now_time, "   -----该日期已有数据")

        return HttpResponse(req, content_type= 'text/html;charset=UTF-8')



def getdataeveryday():
    print('定时任务...')

templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>数据查询</title>
    <link rel="stylesheet" href="/static/layui/css/layui.css" media="all">
    <script src="/static/layui/layui.js"></script>
    <script src="/static/jquery-3.3.1.js"></script>
</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header">
        <div class="layui-logo">数据查询系统</div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        <ul class="layui-nav layui-layout-left">
            <li class="layui-nav-item"><a href="">控制台</a></li>
            <li class="layui-nav-item"><a href="">商品管理</a></li>
            <li class="layui-nav-item"><a href="">用户</a></li>
            <li class="layui-nav-item">
                <a href="javascript:;">其它系统</a>
                <dl class="layui-nav-child">
                    <dd><a href="">邮件管理</a></dd>
                    <dd><a href="">消息管理</a></dd>
                    <dd><a href="">授权管理</a></dd>
                </dl>
            </li>
        </ul>
        <ul class="layui-nav layui-layout-right">
            <li class="layui-nav-item">
                <a href="javascript:;">
                    <img src="http://t.cn/RCzsdCq" class="layui-nav-img">
                    贤心
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="">基本资料</a></dd>
                    <dd><a href="">安全设置</a></dd>
                </dl>
            </li>
            <li class="layui-nav-item"><a href="">退了</a></li>
        </ul>
    </div>

    <div class="layui-side layui-bg-black">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree" lay-filter="test">
                <li class="layui-nav-item layui-nav-itemed">
                    <a class="" href="javascript:;">收入查询</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url 'index:yyrb' %}">医院日报</a></dd>
                        <dd><a href="javascript:;">门诊收入</a></dd>
                        <dd><a href="javascript:;">住院收入</a></dd>
                        <dd><a href="">超链接</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:;">药比查询</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url 'index:zyyb' %}">住院药比(金额)</a></dd>
                        <dd><a href="{% url 'index:zyybbl' %}">住院药比(比例)</a></dd>
                        <dd><a href="{% url 'index:mzyb' %}">门诊药比(金额)</a></dd>
                        <dd><a href="{% url 'index:mzybbl' %}">门诊药比(比例)</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item"><a href="">床位使用率</a></li>
                <li class="layui-nav-item">
                    <a href="javascript:;">人次查询</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url 'index:zyyb' %}">门诊人次</a></dd>
                        <dd><a href="{% url 'index:zyybbl' %}">入院人次</a></dd>
                        <dd><a href="{% url 'index:mzyb' %}">出院人次</a></dd>
                    </dl>
                </li>


            </ul>
        </div>
    </div>

    <div class="layui-body">
        <!-- 内容主体区域 -->
        {% block page-main %}

        {% endblock %}
    </div>

    <div class="layui-footer">
        <!-- 底部固定区域 -->
        © Ray
    </div>
</div>
<script>
    //JavaScript代码区域
    layui.use('element', function () {
        var element = layui.element;

    });
</script>

</body>
</html>